# 服务端口
server:
  port: 8306

  # 服务名
spring:
  application:
    name: service-live

  # 环境设置: dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_live?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #返回json的全局时间格式
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/atguigu/ggkt/live/mapper/xml/*.xml


mtcloud:
  openId: 46537
  openToken:  4ada3d61ae5a5f32ce4901df01f55a6b
